- name: 'apt update'
  shell:
    cmd: 'apt-get update'

- name: 'Remove apache2'
  shell:
    cmd: 'apt --yes remove apache2'

- name: 'install nginx'
  shell:
    cmd: 'apt-get install --yes nginx'

- name: 'check success'
  shell:
    cmd: 'nginx -v'
    
- name: 'start nginx'
  service:
    name: 'nginx'
    state: started