- name: 'apt update'
  shell:
    cmd: 'apt-get update'

- name: 'install nginx'
  shell:
    cmd: 'apt-get install --yes nginx'

- name: 'check success'
  shell:
    cmd: 'nginx -v'

- name: 'copy my config'
  copy:  
    src: "{{ playbook_dir }}/roles/my_nginx/templates/default"
    dest: /etc/nginx/sites-available/
    
- name: 'start nginx'
  service:
    name: 'nginx'
    state: started