- name: 'apt update'
  shell:
    cmd: 'apt update'

- name: 'install MariaDB'
  shell:
    cmd: 'apt install --yes mariadb-server'

- name: 'restart db'
  shell:
    cmd: 'service mariadb restart'

# - name: 'create database ecomdb'
#   mysql_db:
#     login_unix_socket: /var/run/mysqld/mysqld.sock
#     name: ecomdb
#     state: present

# - name: Create database user'
#   mysql_user:
#     login_unix_socket: /var/run/mysqld/mysqld.sock
#     name: ecomuser
#     password: ecompassword
#     priv: '*.*:ALL,GRANT'
#     state: present

- name: 'copy data loader'
  copy:
    src: "{{ playbook_dir }}/roles/my_mariaDB/templates/db-load-script.sql"
    dest: ~/db-load-script.sql

- name: 'run loader'
  shell:
    chdir: '~'
    cmd: 'mysql < db-load-script.sql'





