- name: 'apt update'
  shell:
    cmd: 'apt update'

- name: 'install MariaDB'
  shell:
    cmd: 'apt install --yes mariadb-server'

- name: 'restart db'
  shell:
    cmd: 'service mariadb restart'

- name: 'create database ecomdb'
  mysql_db:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: ecomdb
    state: present

- name: Create database user'
  mysql_user:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: ecomuser
    password: ecompassword
    priv: '*.*:ALL,GRANT'
    state: present

- name: 'copy data loader'
  vars:
    files:
      - name: "create.sql"
      - name: "insert.sql" 
  copy:
    src: "{{ playbook_dir }}/roles/my_mariaDB/templates/{{ item.name }}"
    dest: "~/{{ item.name }}"
  loop: "{{ files }}"
  

- name: 'run loader'
  vars:
    statements:
      - name: 'create.sql'
      - name: 'insert.sql'
  shell:
    chdir: '~'
    cmd: "mysql ecomdb < {{ item.name }}"
  loop: "{{ statements }}"





