# - name: 'clone code'
#   shell:
#     cmd: 'git clone https://github.com/kodekloudhub/learning-app-ecommerce.git /var/www/html/'

- name: 'change ownership'
  shell:
    chdir: /var/www/
    cmd: 'chown -R root:www-data html/' 

- name: 'reload nginx'
  shell:
    cmd: 'service nginx reload'

- name: 'reload php'
  shell:
    cmd: 'service php7.4-fpm reload'