- name: 'install packages'
  vars: 
    commands:
      - name: 'apt-get update'
      - name: 'hwclock --hctosys'
      - name: 'apt-get --yes install python3'
      - name: 'apt-get --yes install python3-pip'
      - name: 'apt-get --yes install python3-mysqldb'
      - name: 'apt-get --yes install python3-pymysql'
      - name: 'python3 -m pip install pymysql'
      - name: 'apt-get --yes install git'
      - name: 'apt-get --yes install php php-cli php-fpm php-json php-common php-mysql php-zip php-gd php-mbstring php-curl php-xml php-pear php-bcmath'
  shell:
    cmd: "{{ item.name }}"
  loop: "{{ commands }}"
  when: ansible_os_family == 'Debian'